name: Secret CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove secrets
        run: |
          cd src/main/resources
          rm secret.properties

      - name: Create secret
        run: |
          cd src/main/resources
          echo "${{ secrets.SECRET }}" > secret.properties
          cat secret.properties
          source .bashrc
          
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}
          gh secret set DOCKER_USERNAME -b ${DOCKER_USERNAME}
          gh secret set DOCKER_PASSWORD -b ${DOCKER_PASSWORD}


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Docker image build
        run: |
          docker build -t ${secrets.DOCKER_USERNAME}/secret .
          docker login -u ${secrets.DOCKER_USERNAME} -p ${secrets.DOCKER_PASSWORD}
          docker push ${secrets.DOCKER_USERNAME}/secret